name: rl4h_rep_new
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311he736701_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py311hda3d55a_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=1.17.1=py311he736701_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.11.11=py311hd8ed1ab_2
  - debugpy=1.8.13=py311hda3d55a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=9.1.0=pyhca29cf9_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - krb5=1.20.1=h5b6d351_0
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libblas=3.9.0=20_win64_mkl
  - libcblas=3.9.0=20_win64_mkl
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - liblapack=3.9.0=20_win64_mkl
  - libpq=17.4=h70ee33d_0
  - libprotobuf=5.29.3=hac4c8cb_0
  - libsodium=1.0.18=h8d14728_1
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.50.0=h2466b09_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxml2=2.13.8=h866ff63_0
  - lightning=2.5.1.post0=pyhd8ed1ab_0
  - lightning-utilities=0.14.3=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.1=py311h130b7e8_1
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.4.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openssl=3.5.0=ha4e3fda_1
  - opentelemetry-api=1.33.0=pyhd8ed1ab_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.1.2=py311hf63dbb6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py311haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - prometheus_client=0.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py311he736701_0
  - psycopg2=2.9.9=py311h827c3e9_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.11=h4607a30_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch-lightning=2.5.1.post0=pyh2a12c56_0
  - pywin32=307=py311hda3d55a_3
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=24.0.1=py311h7b3f143_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.25.1=py311hc4022dc_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.8.0=py311haa95532_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h7e360cc_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h62715c5_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchmetrics=1.7.1=pyhd8ed1ab_0
  - tornado=6.4.2=py311he736701_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - vc=14.42=haa95532_4
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.2=py311he736701_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py311he736701_2
  - pip:
      - absl-py==2.2.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - future==1.0.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - imageio==2.37.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markdown==3.8
      - matplotlib==3.10.1
      - pillow==11.1.0
      - protobuf==6.30.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - threadpoolctl==3.6.0
      - torch==2.1.0+cu118
      - torchdiffeq==0.2.5
      - torchvision==0.16.0+cu118
      - typing-extensions==4.13.0
      - urllib3==2.3.0
      - werkzeug==3.1.3
prefix: D:\Software\anaconda3\envs\rl4h_rep_new
